version: "3.9"
services:
  dev-pool-db:
    image: postgres
    restart: always
    container_name: dev-pool-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
